GET https://tuoitieu.hpcc.vn/models
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyX2VmNDI2NjZlLWQ5YzAtNDVmMS04MmMxLTViMTYzZTIzOGJmOSIsImlhdCI6MTcxNzQxMTAyMH0.5_4_1SMQSfZSJKnNNBox0RvJPHc5l2D1NFkLXW547xc

FARM
###
GET https://tuoitieu.hpcc.vn/farms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyX2VmNDI2NjZlLWQ5YzAtNDVmMS04MmMxLTViMTYzZTIzOGJmOSIsImlhdCI6MTcxNzQxMTAyMH0.5_4_1SMQSfZSJKnNNBox0RvJPHc5l2D1NFkLXW547xc

### 
GET https://tuoitieu.hpcc.vn/farms/farm_06512824-9340-414c-bf5e-649eb973d5b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyX2VmNDI2NjZlLWQ5YzAtNDVmMS04MmMxLTViMTYzZTIzOGJmOSIsImlhdCI6MTcxNzQxMTAyMH0.5_4_1SMQSfZSJKnNNBox0RvJPHc5l2D1NFkLXW547xc

###
